[theme]
primaryColor = "#FFD700"
backgroundColor = "#1a202c"
secondaryBackgroundColor = "#2d3748"
textColor = "#E2E8F0"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
